### ISSUE TITLE
What is the preferred font hosting solution for sites hosted on Github Pages?

### ISSUE THREAD

**Issue by kevinzweerink** [grillitype/web-fonts-guide#1]
Github Pages is a popular way to transform a Github repository into a hosted static site for free. However, in the section ["Uploading Our Font Files to Github"](https://github.com/grillitype/web-fonts-guide#uploading-our-font-files-to-github), you warn against adding font files to public repositories. 

I have contacted another type foundry about this issue in the past, and their response was that it was fine to host their fonts in a public Github repository, since anyone can download the files linked in a `@fontface` declaration, regardless of where they are hosted. However, this was several years ago. Perhaps their policy is an outlier, or perhaps the industry thinking about this has shifted since.

In the case of sites hosted on Github Pages from public repositories, what is GT's recommendation on how and where to host font files?

P.S. this is a great and helpful document, thank you for creating it!

**Comment by grillitype** [comment]
@kevinzweerink Thank you for your kind words! You’re right, in general everyone can download fonts relatively easily anyway. We don’t even require an .htaccess check for the referrer as it’s so easy to get around, too. Still, it’s quite disheartening that you can just search for any typeface on Github and download the fonts so easily – both from unwittingly uploaded and clear piracy-related repos.

If you do have separate private hosting, we’d definitely prefer you upload them there. I’m not sure if this is possible but could they be hosted in a private repo on Github and still be able to get served on a Github Pages site?

**Comment by kevinzweerink** [comment]
@grillitype yeah, totally understand the reasoning! It sucks that Github becomes a tool for stealing fonts, I didn't realize that was going on. Thanks for the clarification.

I think your idea to put the fonts in a separate, private repo and serve that via gh-pages would work! They would be as accessible as if they were hosted anywhere else, but you could keep everything on github without exposing the files in a public repo.

**Comment by grillitype** [comment]
@kevinzweerink You can find a good overview of font piracy on Github [here](https://pixelambacht.nl/2017/github-font-piracy/) – which reminds me that I need to credit that article in this guide too :)

Good to hear that this solution could work!

**Comment by gusbemacbe** [comment]
> I think your idea to put the fonts in a separate, private repo and serve that via gh-pages would work! They would be as accessible as if they were hosted anywhere else, but you could keep everything on github without exposing the files in a public repo.

Hello @kevinzweerink!

I hope you are alive!

Did it work for you?

If I am not wrong, as the GitHub repo is private, the fonts links cannot be loaded in another GitHhub Pages repo or in another site host and end up being inaccessible.

**Comment by adalinesimonian** [comment]
> If I am not wrong, as the GitHub repo is private, the fonts links cannot be loaded in another GitHhub Pages repo or in another site host and end up being inaccessible.

I actually follow this exact pattern with https://ordbokapi.org — the font is hosted in a private repo and served using GitHub Pages, and the public repository for the website references it using CSS.

Sorry to comment on such an old thread, but it shows up in search easily and I figured if the answer is here people will find it easily.

**Comment by gusbemacbe** [comment]
God morgen, @adalinesimonian! 

> I actually follow this exact pattern with https://ordbokapi.org — the font is hosted in a private repo and served using GitHub Pages, and the public repository for the website references it using CSS.

Do you mean `.htaccess` file on the GitHub private repository?

**Comment by adalinesimonian** [comment]
God morgen! Nei, I didn't even need a .htaccess file. All I uploaded was the font files and the CSS file with the font face definition and as you can see on the site it's working.
